using Tyuiu.AymurzinaJV.Sprint3.Task2.V3.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнила: Аймурзина Ю.В. | РППб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                                ");
Console.WriteLine("* Тема: Оператор цикла do-while                                            ");
Console.WriteLine("* Задание #2                                                               ");
Console.WriteLine("* Вариант #3                                                               ");
Console.WriteLine("* Выполнила: Аймурзина Юлия Владимировна | РППб-25-1                       ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                 ");
Console.WriteLine("* Написать программу используя цикл do...while, которая вычисляет сумму    ");
Console.WriteLine("* ряда по формуле, при x = 4                                               ");
Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                         ");
Console.WriteLine("***************************************************************************");
int x = 4;
int startvalue = 1;
int stopvalue = 15;

Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                               ");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.GetSumSeries(x, startvalue, stopvalue));
Console.ReadKey();