using Tyuiu.AymurzinaJV.Sprint3.Task0.V2.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнила: Аймурзина Ю.В. | РППб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                                ");
Console.WriteLine("* Тема: Оператор цикла for                                                 ");
Console.WriteLine("* Задание #0                                                               ");
Console.WriteLine("* Вариант #2                                                               ");
Console.WriteLine("* Выполнила: Аймурзина Юлия Владимировна | РППб-25-1                       ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                 ");
Console.WriteLine("* Написать программу используя цикл for, которая вычисляет произведение    ");
Console.WriteLine("* ряда по формуле.                                                         ");
Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                         ");
Console.WriteLine("***************************************************************************");
int x, y;
Console.WriteLine("Введите значение х:");
x = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите значение y:");
y = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                               ");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.GetMultiplySeries(x, y));
Console.ReadKey();