using Tyuiu.AymurzinaJV.Sprint3.Task4.V3.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнила: Аймурзина Ю.В. | РППб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                                ");
Console.WriteLine("* Тема: Использование операторов continue и break в циклах                 ");
Console.WriteLine("* Задание #4                                                               ");
Console.WriteLine("* Вариант #3                                                               ");
Console.WriteLine("* Выполнила: Аймурзина Юлия Владимировна | РППб-25-1                       ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                 ");
Console.WriteLine("* На отрезке, где x принимает значения от -5 до 5, вычислить значение      ");
Console.WriteLine("* функции y=(cos(x)+sin(x))/x\r\n\r\nПри х = 0 прервать цикл.              ");
Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                         ");
Console.WriteLine("***************************************************************************");
int startValue = -5;
int stopValue = 5;

Console.WriteLine("*                                                                          ");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                               ");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.Calculate(startValue, stopValue));
Console.ReadKey();